#################### Deployment ####################
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: registry.gitlab.com/gitlabodix/cvtheque-gateway-ms-prod
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gitlab-secrets-gateway-ms
#################### Service ####################
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-ms
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080

