spring.application.name=Gateway-MS
server.port=8080
#Register url for client
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.instanceId=:${spring.application.name}:${spring.application.instance_id:${random.value}}

#Zuul Routes : toutes les routes de tous les MS
zuul.prefix=/api

######## Gestion en interne via Controllers ########
#zuul.routes.authentication.url=http://localhost:8001/api/authentication-controller
#zuul.routes.candidat.url=http://localhost:8001/api/candidat
#zuul.routes.candidatsfavoris.url=http://localhost:8001/api/candidatsfavoris
#zuul.routes.candidatsfavoris.url=http://localhost:8001/api/candidat-temporaire-controller
#zuul.routes.collaborateur.url=http://localhost:8001/api/collaborateur
#zuul.routes.contact.url=http://localhost:8001/api/contact
#zuul.routes.partenaire.url=http://localhost:8001/api/partenaire
#zuul.routes.partenaire-temporaire-controller.url=http://localhost:8001/api/partenaire-temporaire-controller

######## Gestion en externe via des MS ########
zuul.routes.opportunite.url=http://localhost:8002/api/opportunite
zuul.routes.opportunitesfavoris.url=http://localhost:8002/api/opportunitesfavoris
zuul.routes.rappel.url=http://localhost:8003/api/rappel

#zuul.routes.opportunite.url=http://localhost:8001/api/opportunite
#zuul.routes.opportunitesfavoris.url=http://localhost:8001/api/opportunitesfavoris
#zuul.routes.rappel.url=http://localhost:8001/api/rappel

zuul.routes.notification.url=http://localhost:8001/api/notification
zuul.routes.projet.url=http://localhost:8001/api/projet
zuul.routes.technologie.url=http://localhost:8001/api/technologie
zuul.routes.entreprise.url=http://localhost:8001/api/entreprise
zuul.routes.ecole.url=http://localhost:8001/api/ecole
zuul.routes.certification.url=http://localhost:8001/api/certification
zuul.routes.chiffrescles.url=http://localhost:8001/api/chiffrescles
zuul.routes.fichier.url=http://localhost:8001/api/fichier

#KAFKA
spring.kafka.bootstrap-servers= localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer

#JWT
jwt.secret=fsdf+34jkk558-gjl57o

#Gmail Server configuration 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=azaheni@smartgraphe.com
spring.mail.password=fsdf+34jkk558-gjl57o
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


#Config Hibernate
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=ERROR
spring.jackson.serialization.fail-on-empty-beans=false

#Tuning Hikari Configuration Parameters
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

###Database : POSTGRESQL
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

###Database : Paramètres partagés
spring.datasource.username=postgres
spring.datasource.password=Az@zel84
spring.datasource.driver-class-name=org.postgresql.Driver

### DEV ###
spring.datasource.url=jdbc:postgresql://localhost:5432/db-gateway-MS

### PROD OVH ###
#spring.datasource.url=jdbc:postgresql://151.80.232.16:5432/db-gateway-MS


#https://www.linkedin.com/developers/apps/13241553/auth
linkedin.consumerKey=77gwc32hbovbzc
linkedin.consumerSecret=lE5VwrZAh7rDQJ2U
linkedin.scope=r_liteprofile r_emailaddress 
linkedin.redirectUri=http://localhost:4200/redirect-linkedin
#linkedin.redirectUri=https://www.odix.tn/redirect-linkedin
linkedin.state=fsdf-34jkk558-gjl57o
#https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin
linkedin.urlLiteProfile=https://api.linkedin.com/v2/me
linkedin.urlEmailaddress=https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))
linkedin.urlProfilePicture=https://api.linkedin.com/v2/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))
