eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}

#Feign
notifications-ms.url: http://localhost:8004
notifications-ms.serviceName=notifications-ms

### Database ###
spring.datasource.url=jdbc:postgresql://localhost:5432/db-gateway-ms
spring.datasource.username=postgres
spring.datasource.password=Az@zel84
spring.datasource.driver-class-name=org.postgresql.Driver


#KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.consumer.group-id=group-gateway-ms
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


#Zuul Routes : toutes les routes.
zuul.prefix=/api
######## Gestion en interne dans la Gateway ########
zuul.routes.gateway/authentication-controller.url=http://localhost:8080/api/gateway/authentication-controller
zuul.routes.gateway/candidat.url=http://localhost:8080/api/gateway/candidat
zuul.routes.gateway/candidatsfavoris.url=http://localhost:8080/api/gateway/candidatsfavoris
zuul.routes.gateway/candidat-temporaire-controller.url=http://localhost:8080/api/gateway/candidat-temporaire-controller
zuul.routes.gateway/collaborateur.url=http://localhost:8080/api/gateway/collaborateur
zuul.routes.gateway/contact.url=http://localhost:8080/api/gateway/contact
zuul.routes.gateway/partenaire.url=http://localhost:8080/api/gateway/partenaire
zuul.routes.gateway/partenaire-temporaire-controller.url=http://localhost:8080/api/gateway/partenaire-temporaire-controller
zuul.routes.gateway/utilisateur.url=http://localhost:8080/api/gateway/utilisateur
################################ Gestion en externe via des MS ################################
##  Backend-MS  ##
zuul.routes.certification.url=http://localhost:8001/api/certification
zuul.routes.ecole.url=http://localhost:8001/api/ecole
zuul.routes.entreprise.url=http://localhost:8001/api/entreprise
zuul.routes.technologie.url=http://localhost:8001/api/technologie
##  Opportunites-MS  ##
zuul.routes.opportunite.url=http://localhost:8002/api/opportunite
zuul.routes.opportunitesfavoris.url=http://localhost:8002/api/opportunitesfavoris
##  Rappels-MS  ##
zuul.routes.rappel.url=http://localhost:8003/api/rappel
zuul.routes.projet.url=http://localhost:8003/api/projet
##  Notifications-MS  ##
zuul.routes.notification.url=http://localhost:8004/api/notification
##  Fichiers-MS  ##
zuul.routes.fichier.url=http://localhost:8005/api/fichier
##  Statistiques-MS  ##
zuul.routes.statistiques.url=http://localhost:8006/api/statistiques



#Linkedin Dev
#https://www.linkedin.com/developers/apps/13241553/auth
linkedin.consumerKey=77gwc32hbovbzc
linkedin.consumerSecret=lE5VwrZAh7rDQJ2U
linkedin.scope=r_liteprofile r_emailaddress 
linkedin.redirectUri=http://localhost:4200/redirect-linkedin
linkedin.state=fsdf-34jkk558-gjl57o
#https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin
linkedin.urlLiteProfile=https://api.linkedin.com/v2/me
linkedin.urlEmailaddress=https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))
linkedin.urlProfilePicture=https://api.linkedin.com/v2/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))



